server:
  port : ${PORT:7090}
  
atp:
  client:
    id: idp-client
    secret: secretKey1
  server:
    host: http://localhost:9090
    #host: https://atp-ist.herokuapp.com
    token-path: /oauth/token